"""nullable_uuid

Revision ID: 251af8030f6d
Revises: 
Create Date: 2026-07-15 16:41:38.242094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '251af8030f6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('document_chunks')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'Foundation'::character varying"))
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("'4 weeks'::character varying"))
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('lessons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('accent',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'indigo'::character varying"))
        batch_op.alter_column('instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('courses_instructor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['instructor_id'], ['id'])

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('enrollments_user_id_course_id_key'), type_='unique')
        batch_op.create_unique_constraint('uq_user_course', ['user_id', 'course_id'])
        batch_op.drop_constraint(batch_op.f('enrollments_course_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('enrollments_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('last_login')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('provider')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('enrollments_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('enrollments_course_id_fkey'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_user_course', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('enrollments_user_id_course_id_key'), ['user_id', 'course_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('courses_instructor_id_fkey'), 'users', ['instructor_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('accent',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'indigo'::character varying"))
        batch_op.alter_column('lessons',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('duration',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'4 weeks'::character varying"))
        batch_op.alter_column('level',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Foundation'::character varying"))
        batch_op.drop_column('updated_at')

    op.create_table('document_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    op.drop_table('projects')
    # ### end Alembic commands ###
